### ISSUE TITLE
Migrate from SQLite to PostgreSQL for production readiness

### ISSUE THREAD

**Issue by sophiedeziel** [sophiedeziel/magic-stack#753]
## Overview
Replace SQLite with PostgreSQL as the default database to provide production-ready data persistence, better performance, and advanced features observed in the dick-watch repository implementation.

## Current State
- Using SQLite for all environments (development, test, production)
- Limited scalability and concurrency support
- Missing advanced database features like full-text search, JSON columns, and complex queries
- Not suitable for production deployment on most hosting platforms

### Database Migration Strategy
- [ ] Replace SQLite with PostgreSQL for all environments
- [ ] Update database configuration for development, test, and production
- [ ] Ensure backward compatibility during transition
- [ ] Provide clear migration instructions

### Dependencies to Update
```ruby
# Gemfile
# Remove: gem 'sqlite3', '~> 2.6'
gem 'pg', '~> 1.5'

group :development, :test do
  # Optional: Keep SQLite for local development only
  # gem 'sqlite3', '~> 2.6', platforms: [:development, :test]
end
```

### Database Configuration
```yaml
# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: magic_stack_development
  username: magic_stack
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: magic_stack_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: magic_stack
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
```

### Docker Support (Optional)
```yaml
# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: magic_stack
      POSTGRES_PASSWORD: password
      POSTGRES_DB: magic_stack_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```

### Environment Configuration
```ruby
# config/initializers/postgresql.rb (if needed)
if Rails.env.production?
  # PostgreSQL-specific optimizations
  ActiveRecord::Base.connection.execute("SET statement_timeout = '30s'")
end
```

## Benefits
- **Production Ready**: Industry standard for production Rails applications
- **Scalability**: Better performance under load and concurrent access
- **Advanced Features**: 
  - Full-text search capabilities
  - JSON/JSONB column support
  - Advanced indexing (GIN, GiST, etc.)
  - Window functions and CTEs
  - Partial indexes and exclusion constraints
- **Reliability**: ACID compliance and data integrity
- **Deployment Support**: Compatible with all major hosting platforms
- **Development Parity**: Same database in all environments reduces bugs

## PostgreSQL Features to Leverage
- [ ] **JSON/JSONB Columns** - For flexible data storage
- [ ] **Full-Text Search** - Built-in search capabilities
- [ ] **Array Columns** - Store arrays natively
- [ ] **UUID Primary Keys** - Better for distributed systems
- [ ] **Partial Indexes** - More efficient indexing
- [ ] **Check Constraints** - Database-level validation

### Example Schema Enhancements
```ruby
# Example migration leveraging PostgreSQL features
class CreateAdvancedUserPreferences < ActiveRecord::Migration[8.0]
  def change
    create_table :user_preferences, id: :uuid do |t|
      t.references :user, null: false, foreign_key: true, type: :uuid
      t.jsonb :settings, null: false, default: {}
      t.text :tags, array: true, default: []
      t.timestamps
    end

    add_index :user_preferences, :settings, using: :gin
    add_index :user_preferences, :tags, using: :gin
  end
end
```

## Implementation Plan
1. **Phase 1**: Update Gemfile and install PostgreSQL gem
2. **Phase 2**: Configure database.yml for PostgreSQL
3. **Phase 3**: Set up local PostgreSQL development environment
4. **Phase 4**: Create database setup scripts and documentation
5. **Phase 5**: Update CI/CD to use PostgreSQL for testing
6. **Phase 6**: Add Docker configuration for easy development setup
7. **Phase 7**: Update deployment documentation

### macOS (Homebrew)
```bash
brew install postgresql@16
brew services start postgresql@16
createuser -s magic_stack
createdb magic_stack_development
```

### Ubuntu/Debian
```bash
sudo apt update
sudo apt install postgresql postgresql-contrib
sudo -u postgres createuser -s magic_stack
sudo -u postgres createdb magic_stack_development
```

### Docker
```bash
docker-compose up -d postgres
```

## Migration Instructions
1. **Backup existing data** (if any)
2. **Install PostgreSQL** locally
3. **Update Gemfile** and run `bundle install`
4. **Update database.yml** configuration
5. **Create databases**: `rails db:create`
6. **Run migrations**: `rails db:migrate`
7. **Seed data**: `rails db:seed` (if applicable)

## Testing Strategy
- [ ] Ensure all existing tests pass with PostgreSQL
- [ ] Add database-specific tests for new PostgreSQL features
- [ ] Test parallel test execution with PostgreSQL
- [ ] Verify performance improvements in test suite

## Production Considerations
- [ ] **Connection Pooling**: Configure pgbouncer or similar
- [ ] **Monitoring**: Set up database monitoring and alerting
- [ ] **Backups**: Implement automated backup strategy
- [ ] **Security**: Configure SSL connections and access controls
- [ ] **Performance**: Optimize queries and add appropriate indexes

## Acceptance Criteria
- [ ] PostgreSQL successfully configured for all environments
- [ ] All existing tests pass with PostgreSQL
- [ ] Database migrations work correctly
- [ ] Development setup documentation updated
- [ ] CI/CD pipeline uses PostgreSQL for testing
- [ ] Production deployment guide includes PostgreSQL setup
- [ ] Optional Docker configuration provided for easy development

## Breaking Changes
- **Development Environment**: Developers will need to install PostgreSQL
- **Deployment**: Production environments must have PostgreSQL available
- **Data Migration**: Existing SQLite data needs to be migrated (if any)

## Related Issues
- Should work seamlessly with Devise authentication (#752)
- Will support future advanced features requiring PostgreSQL
- Enables better performance monitoring and optimization

## Priority
**High** - Essential for production deployments and scalability

---
*This issue is part of the magic-stack template enhancement initiative based on production app learnings.*
